version: '3.7'

services:

  sample:
    container_name: tp-profesional-jf-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 4000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
