version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

jobs:
  deploy:
    docker:
      - image: cimg/base:2021.10
    steps:
      - setup_remote_docker:
          version: 19.03.13
      # deploy
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

workflows:
  heroku_deploy:
    jobs:
      - node/test
      - docker/publish:
          deploy: false
          image: tp-profesional-jf/$CIRCLE_PROJECT_REPONAME
          requires:
            # Build docker after testing.
            - node/test
      - deploy:
          requires:
            - docker/publish
          context: frontend # for env vars
