version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

workflows:
  heroku_deploy:
    jobs:
      - node/test
      - docker/publish:
          deploy: false
          image: tp-profesional-jf/$CIRCLE_PROJECT_REPONAME
          requires:
            # Build docker after testing.
            - node/test
      - heroku/push-docker-image:
          requires:
            # Deploy after publishing.
            - docker/publish
          context: frontend # for env vars
