version: 2.1
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@2.0.1

jobs:
  deploy:
    docker:
      - image: circleci/node:9.5.0-stretch
    steps:
      - setup_remote_docker:
          version: 19.03.13
      # Build the docker image
      - checkout
      - run: docker build .
      # deploy
      - run: npm install firebase-tools
      - run: alias firebase="`npm config get prefix`/bin/firebase"
      - run:
          name: Deploy Master to Firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN 

workflows:
  firebase_deploy:
    jobs:
      - node/test
      - deploy:
          requires:
            - node/test
          context: frontend # for env vars
          filters:
            branches:
              only: main
