version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

jobs:
  # Build the docker image and deploy it to Heroku.
  build_and_deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      # Deploy to Heroku
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

workflows:
  heroku_deploy:
    jobs:
      - node/test
      - docker/publish:
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires:
            # Build docker after testing.
            - node/test
      - build_and_deploy:
          requires:
            # Deploy after publishing.
            - docker/publish
